- name: Install Asterisk
  apt: name=asterisk update_cache=yes state=present
  sudo: yes

- name: Stopping asterisk
  service:
    name: asterisk
    state: stopped

- name: copy files asterisk
  template:
     src=../asterisk/{{ item }}
     dest=/etc/asterisk/{{ item }}

  with_items:
   - "sip.conf"
   - "extensions.conf"
   - "queues.conf"
   - "modules.conf"
   - "iax.conf"
   - "voicemail.conf"

- name: Restarting asterisk
  service:
    name: asterisk
    state: started
